# docker-compose
version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL:sqlite:///instance/fallback.db}  # Fallback to SQLite
      - SECRET_KEY=${SECRET_KEY}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    secrets:
      - username
      - password
      - access_token

secrets:
  username:
    file: ./secrets/username
  password:
    file: ./secrets/password
  access_token:
    file: ./secrets/access_token
