"""empty message

Revision ID: 111b357267c9
Revises: 5e938186ee77
Create Date: 2025-01-19 09:56:02.774521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b357267c9'
down_revision = '5e938186ee77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   #  op.drop_table('_alembic_tmp_dashboard_data')
    with op.batch_alter_table('dashboard_data', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_dashboard_data_user_id",  # Name of the constraint
            "users",  # Referenced table
            ["user_id"],  # Source columns
            ["id"]  # Referenced columns
        )

    with op.batch_alter_table('device_firmware_history', schema=None) as batch_op:
        batch_op.drop_constraint("fk_device_firmware_history_firmware_id", type_="foreignkey")
        batch_op.drop_constraint("fk_device_firmware_history_device_id", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_device_firmware_history_device_id",
            "devices",
            ["device_id"],
            ["id"]
        )
        batch_op.create_foreign_key(
            "fk_device_firmware_history_firmware_id",
            "firmwares",
            ["firmware_id"],
            ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_firmware_history', schema=None) as batch_op:
        batch_op.drop_constraint("fk_device_firmware_history_device_id", type_='foreignkey')
        batch_op.drop_constraint("fk_device_firmware_history_firmware_id", type_='foreignkey')
        batch_op.create_foreign_key(
            "fk_device_firmware_history_firmware_id",
            "firmwares",
            ["firmware_id"],
            ["id"],
            ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_device_firmware_history_device_id",
            "devices",
            ["device_id"],
            ["id"],
            ondelete="CASCADE"
        )

    with op.batch_alter_table('dashboard_data', schema=None) as batch_op:
        batch_op.drop_constraint("fk_dashboard_data_user_id", type_='foreignkey')

    op.create_table('_alembic_tmp_dashboard_data',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('value', sa.INTEGER(), nullable=False),
        sa.Column('description', sa.VARCHAR(length=500), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), nullable=False),
        sa.Column('type', sa.VARCHAR(length=50), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name='fk_dashboard_data_user_id_users'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

