"""empty message

Revision ID: 5e938186ee77
Revises: fa4f0ec582b7
Create Date: 2025-01-18 14:31:20.012263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e938186ee77'
down_revision = 'fa4f0ec582b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_data', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_dashboard_data_user_id_users',  # Constraint name
            'users',  # Referred table
            ['user_id'],  # Local columns
            ['id']  # Referred columns
        )

    with op.batch_alter_table('device_firmware_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_firmware_history_firmware_id_firmwares', type_='foreignkey')
        batch_op.drop_constraint('fk_device_firmware_history_device_id_devices', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_device_firmware_history_firmware_id_firmwares', 
            'firmwares', 
            ['firmware_id'], 
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_device_firmware_history_device_id_devices', 
            'devices', 
            ['device_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_firmware_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_firmware_history_device_id_devices', type_='foreignkey')
        batch_op.drop_constraint('fk_device_firmware_history_firmware_id_firmwares', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_device_firmware_history_device_id_devices', 
            'devices', 
            ['device_id'], 
            ['id'], 
            ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_device_firmware_history_firmware_id_firmwares', 
            'firmwares', 
            ['firmware_id'], 
            ['id'], 
            ondelete='CASCADE'
        )

    with op.batch_alter_table('dashboard_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dashboard_data_user_id_users', type_='foreignkey')
    # ### end Alembic commands ###
