import {test, expect} from '@playwright/test';

test('editable plan runs through Flask and keeps its original version in results', async ({page,request})=>{
  await request.post('/api/lab/runs/cancel',{data:{}});
  await request.post('/api/lab/reset',{data:{}});
  const state=(await(await request.get('/api/lab')).json()).state;
  for(const p of state.testPlans)await request.delete(`/api/lab/test-plans/${p.id}`,{data:{version:p.version}});
  await page.goto('/plans');
  await expect(page.getByText('Flask engine connected')).toBeVisible();
  await page.getByLabel('Plan name',{exact:true}).fill('Valve response check');
  await page.getByLabel('Plan device profile').selectOption('valve');
  await page.getByLabel('Step 1 action').selectOption('set');
  await page.getByLabel('Step 1 value').fill('60');
  await page.getByLabel('Step 2 action').selectOption('assert_equal');
  await page.getByLabel('Step 2 value').fill('60');
  await page.getByRole('button',{name:'Save test plan',exact:true}).click();
  const saved=page.locator('.catalog-item').filter({has:page.getByRole('heading',{name:'Valve response check',exact:true})});
  await expect(saved).toContainText('version 1');
  await page.getByRole('link',{name:'Test bench',exact:true}).click();
  await page.getByLabel('Target device').selectOption({label:'Intake valve'});
  await page.getByRole('button',{name:'Connect device',exact:true}).click();
  await page.getByLabel('Test plan',{exact:true}).selectOption({label:'Valve response check · v1'});
  await page.getByRole('button',{name:'Run test',exact:true}).click();
  await expect(page.locator('.result-heading .status')).toHaveText('passed',{timeout:15000});
  await expect(page.locator('.inspect-reading')).toContainText('0%');
  await page.getByRole('link',{name:'Plan library',exact:true}).click();
  await saved.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Step 1 value').fill('70');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(saved).toContainText('version 2');
  await page.getByRole('link',{name:'Results',exact:true}).click();
  await page.getByText('View saved plan and device settings', {exact:true}).click();
  await expect(page.locator('.run-configuration')).toContainText('"version": 1');
  await expect(page.locator('.run-configuration')).toContainText('"value": 60');
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export this run',exact:true}).click();
  expect((await downloadPromise).suggestedFilename()).toBe('hardware-tester-run.json');
  await page.reload();
  await expect(page.getByText('Configuration used for this run', {exact:true})).toBeVisible();
  await page.goto('/plans');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
