"""Adding valve in there for testing

Revision ID: 2820341e1ab8
Revises: 0b42f4b24865
Create Date: 2025-01-15 21:32:05.085592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2820341e1ab8'
down_revision = '0b42f4b24865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'dashboard_data', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.create_foreign_key(None, 'device_firmware_history', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'device_firmware_history', 'firmwares', ['firmware_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.create_foreign_key(None, 'device_firmware_history', 'firmwares', ['firmware_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_firmware_history', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dashboard_data', type_='foreignkey')
    op.drop_table('valves')
    # ### end Alembic commands ###
