"""New Table ssh

Revision ID: b174350267e0
Revises: f2046c3f19da
Create Date: 2025-01-27 14:01:14.058229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b174350267e0'
down_revision = 'f2046c3f19da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssh_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssh_connections_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssh_connections_name'))

    op.drop_table('ssh_connections')
    # ### end Alembic commands ###
