"""uploaded file

Revision ID: ac663638c6f3
Revises: 94050f153c6f
Create Date: 2025-01-19 21:47:39.749609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac663638c6f3'
down_revision = '94050f153c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
