"""Add available to the controller model

Revision ID: f283a89a6964
Revises: 6badc468d96f
Create Date: 2025-01-21 12:21:11.580902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f283a89a6964'
down_revision = '6badc468d96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
