"""empty message

Revision ID: 2cb4a6f45069
Revises: 5aefd7100a8d
Create Date: 2025-01-06 11:23:53.031589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb4a6f45069'
down_revision = '5aefd7100a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
