"""empty message

Revision ID: 3aa7e2212f58
Revises: 863aba845fe3
Create Date: 2025-01-06 15:11:49.501758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa7e2212f58'
down_revision = '863aba845fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
