"""empty message

Revision ID: 41618f091a15
Revises: a93857ba9cf3
Create Date: 2025-01-05 16:19:26.133979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41618f091a15'
down_revision = 'a93857ba9cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
