"""empty message

Revision ID: 49eae3115c08
Revises: c977dff1b00e
Create Date: 2025-01-05 17:12:51.362096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49eae3115c08'
down_revision = 'c977dff1b00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
