"""empty message

Revision ID: 54b819876548
Revises: 86d020ad4eec
Create Date: 2025-01-06 13:06:36.967517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b819876548'
down_revision = '86d020ad4eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
