"""Updated Init to reflect all current models

Revision ID: 7005397a8791
Revises: 3a5e0f5ff7d0
Create Date: 2025-01-23 22:40:38.529506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7005397a8791'
down_revision = '3a5e0f5ff7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blueprints_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blueprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blueprints_name'))

    # ### end Alembic commands ###
