"""empty message

Revision ID: 7dd24efe1126
Revises: 3aa7e2212f58
Create Date: 2025-01-06 15:13:10.851002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd24efe1126'
down_revision = '3aa7e2212f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
