"""empty message

Revision ID: 863aba845fe3
Revises: 5f266883b738
Create Date: 2025-01-06 14:59:33.283321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863aba845fe3'
down_revision = '5f266883b738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
