"""try another migration

Revision ID: 86d020ad4eec
Revises: 2cb4a6f45069
Create Date: 2025-01-06 12:45:11.521831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d020ad4eec'
down_revision = '2cb4a6f45069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
