"""Dynamic configurations

Revision ID: 90464eacc4c5
Revises: 6a5f9202a0df
Create Date: 2025-01-26 22:45:12.741080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90464eacc4c5'
down_revision = '6a5f9202a0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
