"""Ensure all models autoincrement IDs and correct schema

Revision ID: a8c31f6ecd62
Revises: f8997074dcf6
Create Date: 2025-01-24 14:04:00.829119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c31f6ecd62'
down_revision = 'f8997074dcf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
