"""Moved db

Revision ID: b5d974f608a9
Revises: fdf3e7ce485d
Create Date: 2025-01-06 15:43:57.452374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d974f608a9'
down_revision = 'fdf3e7ce485d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
