"""Auto increment the ids

Revision ID: b79e539fc163
Revises: 7005397a8791
Create Date: 2025-01-24 13:31:54.402470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79e539fc163'
down_revision = '7005397a8791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
