"""empty message

Revision ID: c977dff1b00e
Revises: 41618f091a15
Create Date: 2025-01-05 16:20:11.483553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c977dff1b00e'
down_revision = '41618f091a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
