"""Should be a good foundation

Revision ID: ca3f9e2ba88a
Revises: b5d974f608a9
Create Date: 2025-01-06 19:13:16.946580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3f9e2ba88a'
down_revision = 'b5d974f608a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
