"""Added to dict and repr

Revision ID: f41c26b5269d
Revises: 90464eacc4c5
Create Date: 2025-01-26 22:48:38.257489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41c26b5269d'
down_revision = '90464eacc4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
