"""Updated Models

Revision ID: f7363b37cbc2
Revises: 06723e7640f5
Create Date: 2025-01-06 11:15:08.654782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7363b37cbc2'
down_revision = '06723e7640f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
