"""Updated Blueprint autoupdate features"

Revision ID: f8997074dcf6
Revises: b79e539fc163
Create Date: 2025-01-24 13:58:09.639995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8997074dcf6'
down_revision = 'b79e539fc163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
