"""empty message

Revision ID: fdf3e7ce485d
Revises: 7dd24efe1126
Create Date: 2025-01-06 15:22:01.786062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf3e7ce485d'
down_revision = '7dd24efe1126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
