"""quick migrate test

Revision ID: 2f84cc0c5a15
Revises: 57a5ff4c7722
Create Date: 2025-01-18 14:09:55.169699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f84cc0c5a15'
down_revision = '57a5ff4c7722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('configuration', sa.JSON(), nullable=True))
    op.add_column('blueprints', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('blueprints', sa.Column('version', sa.String(length=50), nullable=True))
    op.add_column('blueprints', sa.Column('author', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'dashboard_data', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.create_foreign_key(None, 'device_firmware_history', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'device_firmware_history', 'firmwares', ['firmware_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.drop_constraint(None, 'device_firmware_history', type_='foreignkey')
    op.create_foreign_key(None, 'device_firmware_history', 'firmwares', ['firmware_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_firmware_history', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dashboard_data', type_='foreignkey')
    op.drop_column('blueprints', 'author')
    op.drop_column('blueprints', 'version')
    op.drop_column('blueprints', 'updated_at')
    op.drop_column('blueprints', 'configuration')
    # ### end Alembic commands ###
