import {useEffect,useState} from 'react';

export interface Account {id:string;username:string;email:string;role:'viewer'|'operator'|'admin';enabled:boolean;version:number}
export interface Session {enabled:boolean;setupRequired:boolean;user:Account|null;csrf:string|null}
let csrf='';
export async function authRequest(path:string,method='GET',data?:unknown) {
  const response=await fetch('/api/auth'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(10000)});
  const result=await response.json();
  if(!response.ok)throw new Error(result.error||'Account request failed.');
  if('csrf' in result)csrf=result.csrf||'';
  return result;
}
export function csrfToken(){return csrf;}

export function SignIn({session,onSession,error:connectionError=''}:{session:Session|undefined;onSession:(s:Session)=>void;error?:string}) {
  const [username,setUsername]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  return <section className="panel settings-panel"><h2>{session?.setupRequired?'Create the first admin':'Sign in to HardwareTester'}</h2><p>{session?.setupRequired?'This account will manage users and the shared workspace. Passwords require 12–128 characters.':'Use your account for this backend. Sessions last eight hours.'}</p>{(error||connectionError)&&<p role="alert" className="helper danger">{error||connectionError}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await authRequest(session?.setupRequired?'/setup':'/login','POST',{username,email,password});setPassword('');onSession(result);}catch(e){setError(e instanceof Error?e.message:'Sign in failed.');}finally{setBusy(false);}}}>
    <label>Username<input aria-label="Sign in username" required autoComplete="username" value={username} maxLength={50} onChange={e=>setUsername(e.target.value)}/></label>{session?.setupRequired&&<label>Email<input aria-label="Admin email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>Password<input aria-label="Sign in password" type="password" required minLength={session?.setupRequired?12:1} maxLength={128} autoComplete={session?.setupRequired?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary" disabled={busy||!session}>{busy?'Signing in…':session?.setupRequired?'Create admin':'Sign in'}</button></form></section>;
}

export function UserManagement({onChange}:{onChange:()=>void}) {
  const [users,setUsers]=useState<Account[]>([]);const [username,setUsername]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<Account['role']>('viewer');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){try{setUsers((await authRequest('/users')).users);}catch(e){setError(e instanceof Error?e.message:'Could not load accounts.');}}
  useEffect(()=>{void load();},[]);
  async function update(user:Account,changes:Record<string,unknown>){setBusy(true);setError('');try{const result=await authRequest(`/users/${user.id}`,'PATCH',{version:user.version,...changes});setUsers(result.users);onChange();}catch(e){setError(e instanceof Error?e.message:'Account update failed.');await load();}finally{setBusy(false);}}
  return <section className="panel settings-panel" style={{marginTop:24}}><h2>User accounts</h2><p>Viewers inspect and export. Operators connect devices and run tests. Admins manage configuration and accounts. Password changes and disabling accounts revoke their sessions.</p>{error&&<p className="helper danger" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await authRequest('/users','POST',{username,email,password,role});setUsers(result.users);setUsername('');setEmail('');setPassword('');}catch(e){setError(e instanceof Error?e.message:'Could not create account.');}finally{setBusy(false);}}}><label>New username<input aria-label="New username" required value={username} maxLength={50} onChange={e=>setUsername(e.target.value)}/></label><label>Email<input aria-label="New user email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Temporary password<input aria-label="New user password" type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Role<select aria-label="New user role" value={role} onChange={e=>setRole(e.target.value as Account['role'])}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option></select></label><button className="button primary" disabled={busy}>Create account</button></form>
    {users.map(u=><article className="catalog-item" key={u.id}><h3>{u.username}</h3><p>{u.email} · {u.enabled?'Enabled':'Disabled'}</p><div className="inline"><label>Role<select aria-label={`Role for ${u.username}`} value={u.role} disabled={busy} onChange={e=>void update(u,{role:e.target.value})}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option></select></label><button className="button secondary" disabled={busy} onClick={()=>{if(confirm(`${u.enabled?'Disable':'Enable'} ${u.username}?`))void update(u,{enabled:!u.enabled});}}>{u.enabled?'Disable':'Enable'}</button></div><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const password=String(new FormData(form).get('password'));await update(u,{password});form.reset();}}><label>Reset password<input aria-label={`Password for ${u.username}`} name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button className="button secondary" disabled={busy}>Set password</button></form></article>)}
  </section>;
}
