import {ReactNode,useId,useState} from 'react';
import {FiChevronDown,FiInfo} from 'react-icons/fi';
import {PlanStep} from './backend';
export const stepActions={read:'Read telemetry',set:'Set output',assert_range:'Check range',assert_equal:'Check expected value',wait:'Wait to settle'};
export function stepSummary(s:PlanStep){return s.action==='wait'?`Wait ${s.seconds??1}s`:s.action==='set'?`Output ${s.value??0} · timeout ${s.timeout??2}s`:s.action==='assert_equal'?`Expected ${s.value??0} ± ${s.tolerance??0} · timeout ${s.timeout??2}s`:s.action==='assert_range'?`Range ${s.min??0}–${s.max??50} · timeout ${s.timeout??2}s`:`Read telemetry · timeout ${s.timeout??2}s`;}
export default function PlanStepRow({step,index,open,onToggle,error,children}:{step:PlanStep;index:number;open:boolean;onToggle:()=>void;error?:string;children?:ReactNode}){
  const id=useId();const [preview,setPreview]=useState(false);
  return <article className={`plan-index-row ${open?'is-open':''} ${error?'has-error':''}`}><div className="plan-index-header"><button className="plan-index-toggle" aria-label={`${children?'Edit':'View'} step ${index+1}: ${step.name||'Unnamed step'}`} aria-expanded={open} aria-controls={`${id}-editor`} onClick={onToggle}><span className="plan-step-number">{String(index+1).padStart(2,'0')}</span><span className="plan-step-title"><strong>{step.name||'Unnamed step'}</strong><small>{stepActions[step.action]}</small></span><span className={`plan-action-badge ${step.action}`}>{step.action.replace('assert_','check ').replace('_',' ')}</span><FiChevronDown/></button><div className="plan-preview" onMouseEnter={()=>setPreview(true)} onMouseLeave={()=>setPreview(false)}><button className="plan-preview-button" aria-label={`Preview step ${index+1}: ${step.name||'Unnamed step'}`} aria-describedby={preview?`${id}-preview`:undefined} onFocus={()=>setPreview(true)} onBlur={()=>setPreview(false)} onClick={()=>setPreview(true)} onKeyDown={e=>{if(e.key==='Escape')setPreview(false);}}><FiInfo/></button>{preview&&<div id={`${id}-preview`} role="tooltip" className="plan-step-tooltip"><b>{step.name||'Unnamed step'}</b><span>{stepSummary(step)}</span>{error&&<span className="danger">{error}</span>}<small>{children?'Expand the row to edit this step.':'Expand the row for step details.'}</small></div>}</div></div>{error&&<p className="plan-step-error" role="alert">{error}</p>}{open&&<div className="plan-index-body" id={`${id}-editor`}>{children??<p>{stepSummary(step)}</p>}</div>}</article>;
}
export function SavedSteps({steps}:{steps:PlanStep[]}){
  const [visible,setVisible]=useState(false);const [open,setOpen]=useState<Set<number>>(new Set());
  return <div className="saved-step-index"><button className="text-button" aria-expanded={visible} onClick={()=>setVisible(!visible)}>{visible?'Hide steps':'View steps'} · {steps.length}</button>{visible&&steps.map((step,index)=><PlanStepRow key={index} step={step} index={index} open={open.has(index)} onToggle={()=>setOpen(previous=>{const next=new Set(previous);next.has(index)?next.delete(index):next.add(index);return next;})}/>)}</div>;
}
