import {test,expect} from '@playwright/test';
test('reports show recorded measurements, rerun their target, and filter linked logs',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('hardware-tester.engine','browser'));
  await page.goto('/overview');
  await page.getByRole('button',{name:'Connect bench',exact:true}).click();
  await page.getByLabel('Target device').selectOption({label:'Intake valve'});
  await page.getByLabel('Test plan',{exact:true}).selectOption('control');
  await page.getByRole('button',{name:'Run test',exact:true}).click();
  await expect(page.locator('.result-heading .status')).toHaveText('passed');
  await page.getByRole('link',{name:'Results',exact:true}).click();
  const report=page.getByRole('region',{name:'Run report'});
  await expect(report.locator('.report-verdict')).toHaveText('passed');
  await expect(report).toContainText('Restored');
  await expect(report.getByRole('img',{name:'Actual 75%; expected 75% ± 0'})).toBeVisible();
  if(await page.getByRole('button',{name:'Dismiss notification'}).count())await page.getByRole('button',{name:'Dismiss notification'}).click();
  if(process.env.LAB_SCREENSHOT_DIR)await report.screenshot({path:`${process.env.LAB_SCREENSHOT_DIR}/hardware-tester-run-report.png`});
  await page.getByRole('link',{name:'Test bench',exact:true}).click();
  await page.getByLabel('Target device').selectOption({label:'Ambient temperature'});
  await page.getByRole('link',{name:'Results',exact:true}).click();
  await report.getByRole('button',{name:'Rerun test',exact:true}).click();
  await expect(report.locator('.report-verdict')).toHaveText('running');
  await expect(report.getByRole('button',{name:'Rerun test',exact:true})).toBeDisabled();
  await expect(report.locator('.report-verdict')).toHaveText('passed');
  await expect(report.getByRole('heading',{name:'Intake valve',exact:true})).toBeVisible();
  await expect(page.locator('tbody tr')).toHaveCount(2);
  await report.getByRole('button',{name:'View run logs'}).click();
  await expect(page.getByLabel('Filter log run')).toHaveValue('selected');
  await expect(page.locator('.log-line')).toHaveCount(5);
  await page.getByLabel('Search logs').fill('Verify response');
  await expect(page.locator('.log-line')).toHaveCount(1);
  await page.getByLabel('Filter logs').selectOption('error');
  await expect(page.getByText('No events match these filters.')).toBeVisible();
  await page.getByRole('button',{name:'Clear filters',exact:true}).click();
  await page.getByLabel('Sort logs').selectOption('oldest');
  await expect(page.locator('.log-line').first()).toContainText('Connected');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.getByRole('link',{name:'Results',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.getByRole('link',{name:'Devices',exact:true}).click();
  await page.getByLabel('Fault injection').selectOption('timeout');
  await page.getByRole('link',{name:'Results',exact:true}).click();
  await expect(report).toContainText('Configuration changed since this run.');
  page.once('dialog',dialog=>dialog.dismiss());
  await report.getByRole('button',{name:'Rerun test',exact:true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(2);
});
